#! /bin/bash

bspc config normal_border_color "#282828"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#fbf1c7"
bspc config presel_feedback_color "#fbf1c7"

bspc config initial_polarity first_child
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

bspc config center_pseudo_tiled false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 1
bspc config window_gap 20

if [ $(bspc query -M | wc -l) -gt 1 ]; then
	bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9
	bspc monitor eDP1 -d 0
else
	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
fi
