#! /bin/bash
#
# Panel Colors
#

#Gruvbox Dark
panel_color_0="#282828"
panel_color_1="#cc241d"
panel_color_2="#98971a"
panel_color_3="#d79921"
panel_color_4="#458588"
panel_color_5="#b16286"
panel_color_6="#689d6a"
panel_color_7="#a89984"
panel_color_8="#928374"
panel_color_9="#fb4934"
panel_color_10="#b8bb26"
panel_color_11="#fabd2f"
panel_color_12="#83a598"
panel_color_13="#d3869b"
panel_color_14="#8ec07c"
panel_color_15="#ebdbb2"
panel_color_fg="#fbf1c7"
panel_color_bg="#282828"

#Gruvbox Light
#panel_color_0="#fbf1c7"
#panel_color_1="#cc241d"
#panel_color_2="#98971a"
#panel_color_3="#d79921"
#panel_color_4="#458588"
#panel_color_5="#b16286"
#panel_color_6="#689d6a"
#panel_color_7="#7c6f64"
#panel_color_8="#928374"
#panel_color_9="#9d0006"
#panel_color_10="#79740e"
#panel_color_11="#b57614"
#panel_color_12="#076678"
#panel_color_13="#8f3f71"
#panel_color_14="#427b58"
#panel_color_15="#3c38c6"
#panel_color_fg="#282828"
#panel_color_bg="#fbf1c7"
