#! /bin/zsh
#
# ~/.zshrc
#

[[ ! -o interactive ]] && return

[ "$_HAVE_ZPROFILE" != "true" ] && [ -e "$HOME/.zprofile" ] && source "$HOME/.zprofile"

HISTFILE=~/.zsh_history
HISTSIZE=250
SAVEHIST=250

unsetopt beep

autoload -Uz compinit promptinit
compinit
promptinit

prompt walters
alias ls='ls --color=auto'
alias svim='sudo vim'
alias ncmpc='ncmpc --host=$MPD_HOST'

unset _HAVE_ZPROFILE
